### PR TITLE
Fix/release pipeline

### PR DESCRIPTION
**Pull request by calebkiage**

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
could we use main instead?

**Comment by calebkiage** [comment]
We could, but there's no way of versioning. If we used main and someone wanted to re-run a pipeline, the wrong workflow could be selected.

**Comment by baywet** [comment]
ah and you're stuck because the tag was already created and if we remove the version all together it will select the version of the current tag, correct? So the only way to "properly" fix that would be to re-tag.

**Comment by calebkiage** [comment]
I mean in future. Say we're on version 2 which changes the sign-binary workflow to need new inputs, if we wanted to run a version 1 workflow, the pipeline would use the latest version of the sign-binary workflow in main and that means the required inputs that were added in version 2 will break the workflow. We aren't versioning the workflow files at the moment.

**Comment by baywet** [comment]
That's the point of configuration as code,  have it evolve and be in sync with the code.  Locking things to specific versions seems to go against that

**Comment by calebkiage** [comment]
I understand that, but I think including a workflow in another workflow is a special case. According to the GitHub docs,

> - Using the commit SHA of a released action version is the safest for stability and security.

**Review by baywet — APPROVED** [review]

**Pull request merged**
