### PR TITLE
Generate code with new composable commands

### PR DESCRIPTION
**Pull request by calebkiage**

### CODE REVIEW

**Comment by baywet** [comment]
@calebkiage before you merge, can you check whether you've been impacted by https://github.com/microsoft/OpenAPI.NET.OData/issues/366 in your latest generation?

**Comment by calebkiage** [comment]
This isn't based on the latest OpenAPI schema. I'll regenerate and confirm.

**Comment by baywet** [comment]
Thanks for confirming. The description we currently have (and any generation using the pipeline) will have the issue at this point.

**Comment by calebkiage** [comment]
Do you know what the last working version is? I can use that. Also, the CLI shouldn't be affected that badly. I think the impact will be that the CLI won't show anything after the command completes. The expected behavior is to show a success message.

**Comment by baywet** [comment]
Commits on April 4th are wrong, before that should be good. https://github.com/microsoftgraph/msgraph-metadata/commits/master

**Pull request merged**
