### PR TITLE
Update generated code.

### PR DESCRIPTION
**Pull request by calebkiage**
Schema version: microsoftgraph/msgraph-metadata@c042ff7b
Generator version: microsoft/kiota@8e21ff5c

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
It's a great set of changes, the CLI is most likely going to be much more resiliant. I think the only pattern that we'd probably change is the following
`CSharp
var response = await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping: errorMapping, cancellationToken: cancellationToken) ?? Stream.Null;
response = (response is not null) ? await outputFilter.FilterOutputAsync(response, query, cancellationToken) : response;
`
response at the first line will never be null, so the second line will always apply the filter. We might want to compare the reference to stream.null instead or always call the filtering logic if it handles empty streams gracefully

**Comment by calebkiage** [comment]
Hey Vincent, I can add a check against `Stream.Null`

**Review by baywet — DISMISSED** [review]
LGTM. You're probably impacted by https://github.com/microsoft/kiota/issues/2234 but this is probably an edge case (excel endpoints only) that'll resolve itself whenever it's fixed

**Comment by calebkiage** [comment]
I wonder if we should wait on https://github.com/microsoft/kiota/pull/2251

**Review by baywet — APPROVED** [review]

**Pull request merged**
